Renegade/Engine.cpp
Renegade/Renegade.vcxproj
Renegade/Renegade.vcxproj.filters
Renegade/Search.cpp
Renegade/Settings.cpp
Renegade/Settings.h

Very basic search tuning support

---

Renegade/Board.cpp
Renegade/Board.h
Renegade/Engine.cpp
Renegade/Move.h
Renegade/Position.cpp
Renegade/Position.h
Renegade/Reporting.cpp
Renegade/Search.cpp
Renegade/Settings.cpp
Renegade/Settings.h
Renegade/Utils.h

Seems to be working fine, but for the time being it's just pretty bad at it. 
Standard chess is unaffected, no functional changes there.
1.1.0 dev 22
Bench: 3204070

Chess960 support

---

Renegade/Search.cpp
Renegade/Utils.h

Legendary gainer (lol)
```
Elo   | 2.14 +- 2.23 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 41800 W: 9541 L: 9284 D: 22975
Penta | [194, 4758, 10773, 4947, 228]
https://renegadedev.eu.pythonanywhere.com/test/95/
```
Renegade dev 1.0.26
Bench: 3449575

Don't futility prune for moves with high history

---

Renegade/Datagen.cpp
Renegade/Engine.cpp
Renegade/Engine.h
Renegade/Search.cpp
Renegade/Search.h
Renegade/Transpositions.cpp
Renegade/Transpositions.h

Note: this patch temporarily removes the ability to respond to stop or isready
Renegade dev 1.1.11
Bench: 3316827

Preparations for future multithreaded search support

---

Renegade/Engine.cpp
Renegade/Neural.h
Renegade/Utils.h
renegade-net.rs

```
Elo   | 3.39 +- 2.56 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 4.00]
Games | N: 19998 W: 4625 L: 4430 D: 10943
Penta | [123, 2272, 4983, 2529, 92]
https://zzzzz151.pythonanywhere.com/test/884/
```
Renegade dev 1.1.18
Bench: 3041741

Net 25: train on 850 million new positions, 3.6 billion in total

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 5.79 +- 3.57 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 9294 W: 2061 L: 1906 D: 5327
Penta | [21, 1014, 2438, 1137, 37]
https://zzzzz151.pythonanywhere.com/test/1057/
```
Renegade dev 1.1.23
Bench: 3037862

Add capture history

---

Renegade/Neural.h
Renegade/Utils.h
renegade-net.rs

```
Elo   | 16.18 +- 6.47 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 4.00]
Games | N: 3072 W: 780 L: 637 D: 1655
Penta | [7, 317, 759, 432, 21]
https://zzzzz151.pythonanywhere.com/test/1297/
```
Renegade dev 1.1.41
Bench: 2850752

Net 26: regenerating the oldest 1 billion positions

---

Renegade/Datagen.cpp
Renegade/Datagen.h
Renegade/Engine.cpp
Renegade/Engine.h
Renegade/Neural.h
Renegade/Utils.h

This merges existing datagen settings into the main branch, such as:
- randomizing node limits
- using a book for non-DFRC datagen
- adjusted random move counts at the beginning
Renegade dev 1.1.43
Bench: 2877006

Unify main and datagen branches (both normal and DFRC)

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Utils.h

```
Elo   | 2.12 +- 2.59 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=8MB
LLR   | 2.90 (-2.25, 2.89) [-3.50, 0.00]
Games | N: 16410 W: 3832 L: 3732 D: 8846
Penta | [68, 1612, 4763, 1676, 86]
https://zzzzz151.pythonanywhere.com/test/1630/
```
Renegade dev 1.1.58
Bench: 2993425

Change piece encodings to something more sane

---

Renegade/Engine.cpp
Renegade/Neural.cpp
Renegade/Neural.h
Renegade/Renegade.cpp
Renegade/Utils.h

Also clearing up the logic a bit while we're at it.
```
Elo   | 5.31 +- 3.23 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=8MB
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.50]
Games | N: 11900 W: 2863 L: 2681 D: 6356
Penta | [51, 1280, 3125, 1424, 70]
https://zzzzz151.pythonanywhere.com/test/1776/
```
Renegade dev 1.1.77
Bench: 2792538

Caching accumulators for each bucket (aka Finny tables)

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

Stress tests vs insta moving opponent:
https://zzzzz151.pythonanywhere.com/test/2061/
https://zzzzz151.pythonanywhere.com/test/2062/
Renegade dev 1.1.97
Bench: 4222214

Fix rare engine stalls due to opponent being too quick

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Movepicker.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.69 +- 1.96 (95%)
Games | N: 30892 W: 7073 L: 6834 D: 16985
Penta | [71, 3552, 7970, 3773, 80]
https://zzzzz151.pythonanywhere.com/test/2159/
```
Renegade dev 1.1.102
Bench: 4604778

Search tune (76k games @ 10+0.1)

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Movepicker.h
Renegade/Search.cpp
Renegade/Settings.h
Renegade/Utils.h

```
Elo   | 4.16 +- 2.59 (95%)
SPRT  | 50.0+0.50s Threads=1 Hash=128MB
Games | N: 16686 W: 3782 L: 3582 D: 9322
Penta | [7, 1886, 4360, 2080, 10]
https://zzzzz151.pythonanywhere.com/test/2228/
```
Renegade dev 1.1.105
Bench: 4767679

Search tune (75k games @ 50+0.5)

---

Renegade/Board.cpp
Renegade/Board.h
Renegade/Engine.cpp
Renegade/Position.cpp
Renegade/Position.h
Renegade/Utils.h

Renegade dev 1.1.106
Bench: 4767679

Move threats and hash into `Board`

---

Renegade/Datagen.cpp
Renegade/Engine.cpp
Renegade/Search.cpp
Renegade/Transpositions.cpp
Renegade/Transpositions.h
Renegade/Utils.h

Renegade dev 1.1.109
Bench: 4575394

Multithreaded initialization support for the TT

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Movepicker.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.14 +- 1.67 (95%)
Games | N: 43514 W: 9870 L: 9602 D: 24042
Penta | [102, 5163, 10964, 5421, 107]
https://zzzzz151.pythonanywhere.com/test/2432/
```
Renegade dev 1.1.113
Bench: 5301904

Introduce a new kind of refutation move based on pawn hash

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 3.26 +- 2.19 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=8MB
Games | N: 21642 W: 5269 L: 5066 D: 11307
Penta | [76, 1977, 6543, 2118, 107]
https://zzzzz151.pythonanywhere.com/test/2660/
```
Renegade dev 1.1.122
Bench: 5120119

Template pvNode in search

---

Renegade/Position.cpp
Renegade/Position.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 3.60 +- 2.37 (95%)
Games | N: 19866 W: 4620 L: 4414 D: 10832
Penta | [49, 2082, 5465, 2288, 49]
https://zzzzz151.pythonanywhere.com/test/2675/
```
Renegade dev 1.1.123
Bench: 5287916

Improve repetition detection

---

Renegade/Board.cpp
Renegade/Board.h
Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Position.cpp
Renegade/Position.h
Renegade/Utils.h

```
Elo   | 5.27 +- 3.03 (95%)
Games | N: 13396 W: 3173 L: 2970 D: 7253
Penta | [37, 1523, 3378, 1720, 40]
https://zzzzz151.pythonanywhere.com/test/2682/
```
Renegade dev 1.1.124
Bench: 5627061

Replace material corrhist with non-pawn corrhist

---

Renegade/Search.cpp
Renegade/Utils.h

Renegade dev 1.1.131
Bench: 4510003

Fix an edge case when checking for the soft time limit

---

Renegade/Neural.cpp
Renegade/Neural.h
Renegade/Utils.h

Renegade dev 1.1.135
Bench: 4906738

Simplify neural network loading
