Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 6.11 +- 5.15 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 7846 W: 1831 L: 1693 D: 4322
Penta | [53, 835, 2018, 955, 62]
https://renegadedev.eu.pythonanywhere.com/test/7/
```
1.1.0 dev 10
Bench: 2147010

Adjust reductions based on ply+1's fail-high count

---

Renegade/Board.cpp
Renegade/Utils.h

```
Elo   | 9.84 +- 7.74 (95%)
SPRT  | 6.0+0.06s Threads=1 Hash=16MB
LLR   | 2.97 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 3392 W: 792 L: 696 D: 1904
Penta | [15, 351, 882, 419, 29]
https://renegadedev.eu.pythonanywhere.com/test/16/
```

Remove obsolete en passant threats code

---

Renegade/Heuristics.cpp
Renegade/Heuristics.h
Renegade/Utils.h

This removes the move ordering method that was used before the implementation of history heuristic. It was used as a fallback in the case of history score = 0 until now.
The test takes the high score for the longest running SPRT so far, easily beating the previous record of 18k games:
```
Elo   | -0.46 +- 2.21 (95%)
SPRT  | 6.0+0.06s Threads=1 Hash=16MB
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 43394 W: 9890 L: 9948 D: 23556
Penta | [319, 5208, 10715, 5122, 333]
```
1.1.0 dev 12
Bench: 2582202

Remove move ordering fallback when no history scores exist

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.72 +- 2.72 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 27894 W: 6339 L: 6121 D: 15434
Penta | [178, 3253, 6869, 3467, 180]
https://renegadedev.eu.pythonanywhere.com/test/22/
```
1.1.0 dev 13
Bench: 2169826

Smaller aspiration windows, and widening it less

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 16.67 +- 9.30 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2482 W: 634 L: 515 D: 1333
Penta | [8, 262, 599, 347, 25]
https://renegadedev.eu.pythonanywhere.com/test/24/
```
1.1.0 dev 14
Bench: 2147382

Double extensions

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 5.78 +- 4.97 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8530 W: 2012 L: 1870 D: 4648
Penta | [43, 984, 2088, 1088, 62]
https://renegadedev.eu.pythonanywhere.com/test/37/
```
1.1.0 dev 19
Bench: 2265307

When improving, reduce move count before LMP kicks in

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 3.77 +- 3.73 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 15134 W: 3519 L: 3355 D: 8260
Penta | [70, 1729, 3835, 1833, 100]
https://renegadedev.eu.pythonanywhere.com/test/51/
```
1.1.0 dev 20
Bench: 2098685

Aspiration reduce depth

---

Renegade/Neurals.cpp
Renegade/Neurals.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 19.14 +- 10.02 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2180 W: 574 L: 454 D: 1152
Penta | [11, 214, 525, 324, 16]
https://renegadedev.eu.pythonanywhere.com/test/128/
```
Renegade dev 1.1.3
Bench: 3076641

Net 23: input buckets based on the king's position

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Search.cpp
Renegade/Utils.h

Elo   | 1.28 +- 3.75 (95%)
LLR   | 2.97 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 14366 W: 3162 L: 3109 D: 8095
Penta | [58, 1651, 3716, 1696, 62]
https://renegadedev.eu.pythonanywhere.com/test/130/
Renegade dev 1.1.4
Bench: 4806289

Simplify away the second killer move

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 8.61 +- 6.64 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 4762 W: 1139 L: 1021 D: 2602
Penta | [13, 481, 1283, 583, 21]
https://renegadedev.eu.pythonanywhere.com/test/145/
```
Renegade dev 1.1.8
Bench: 3316827

Increase the minimum time usage

---

Renegade/Board.cpp
Renegade/Board.h
Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Position.h
Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

Correct static evaluation based on material count history
Elo   | 7.59 +- 4.20 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 6778 W: 1559 L: 1411 D: 3808
Penta | [16, 731, 1755, 863, 24]
Bench: 2906830

Material correction history

---

Renegade/Datagen.cpp
Renegade/Datagen.h
Renegade/Engine.cpp
Renegade/Engine.h
Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Reporting.cpp
Renegade/Reporting.h
Renegade/Search.cpp
Renegade/Search.h
Renegade/Settings.h
Renegade/Utils.h

This commit finally adds support for multithreaded search. The primary motivation is to make use of the beefy hardware at TCEC Swiss 7 playoffs.
The code is rather terrible, and there seems to be some rare stalls that are difficult to track down. Some features (datagen, perft) have also been temporarily disabled. These issues will be addressed in follow-up commits, as not to hinder further progress.
**Scaling tests for an earlier version:**
2 threads vs 1 thread:
```
Elo   | 79.90 +- 10.91 (95%)
Conf  | 10.0+0.10s Threads=2 Hash=32MB
Games | N: 1000 W: 333 L: 107 D: 560
Penta | [0, 39, 209, 239, 13]
https://zzzzz151.pythonanywhere.com/test/927/
```
8 threads vs 1 thread:
```
Elo   | 167.10 +- 10.40 (95%)
Conf  | 10.0+0.10s Threads=8 Hash=32MB
Games | N: 1000 W: 474 L: 27 D: 499
Penta | …
```

Preliminary support for multithreaded search

---

Renegade/Search.cpp
Renegade/Transpositions.cpp
Renegade/Transpositions.h
Renegade/Utils.h

```
Elo   | 3.00 +- 2.22 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 18298 W: 4004 L: 3846 D: 10448
Penta | [32, 1572, 5784, 1728, 33]
https://zzzzz151.pythonanywhere.com/test/1072/
```
Renegade dev 1.1.24
Bench: 3037862

Save raw evaluation into the transposition table

---

Renegade/Board.cpp
Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Position.h
Renegade/Utils.h

```
Elo   | 4.73 +- 3.19 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 12272 W: 2759 L: 2592 D: 6921
Penta | [42, 1390, 3112, 1543, 49]
https://zzzzz151.pythonanywhere.com/test/1109/
```
Renegade dev 1.1.29
Bench: 3042528

Pawn structure correction history

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 2.99 +- 2.32 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 4.00]
Games | N: 23136 W: 5239 L: 5040 D: 12857
Penta | [82, 2666, 5882, 2847, 91]
https://zzzzz151.pythonanywhere.com/test/1125/
```
Renegade dev 1.1.31
Bench: 2865493

Keep track of cutnodes as well & use them in LMR

---

Renegade/Datagen.cpp
Renegade/Datagen.h
Renegade/Engine.cpp
Renegade/Engine.h
Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

This commit reenables the datagen functionality, and makes some additional changes:
- adds win and draw adjudication
- implements a quick start feature with default parameters if launched with `Renegade.exe bench`
- rewrites some old code
- adds a singlethreaded (blocking) search function, currently used by datagen and bench
A follow-up commit is being tested to make datagen require an opening book
Renegade dev 1.1.32
Bench: 2865493

Reenable and improve datagen

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Utils.h

Also dubbed as "concorrde", orginally passed in Motor, and it's based on ideas from a recent ice4 gainer.
I think Renegade might be the second engine to have this?
```
Elo   | 2.38 +- 1.92 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 33274 W: 7400 L: 7172 D: 18702
Penta | [101, 3855, 8512, 4053, 116]
https://zzzzz151.pythonanywhere.com/test/1181/
```
Renegade dev 1.1.34
Bench: 2856903

Correction history indexed by the previous two moves

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Utils.h

```
Elo   | 3.35 +- 2.51 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 19200 W: 4217 L: 4032 D: 10951
Penta | [50, 2179, 4983, 2312, 76]
https://zzzzz151.pythonanywhere.com/test/1221/
```
Renegade dev 1.1.38
Bench: 2873887

Using threats in capture history

---

Renegade/Search.cpp

Elo   | 3.16 +- 2.40 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 4.00]
Games | N: 21248 W: 4688 L: 4495 D: 12065
Penta | [75, 2418, 5432, 2637, 62]

Cutnode negative extension

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 9.06 +- 4.74 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 5790 W: 1354 L: 1203 D: 3233
Penta | [20, 647, 1421, 776, 31]
https://zzzzz151.pythonanywhere.com/test/1272/
```
Renegade dev 1.1.40
Bench: 2451366

Adjust SEE margin in move ordering based on capthist

---

Renegade/Board.cpp
Renegade/Board.h
Renegade/Position.cpp
Renegade/Utils.h

Non-final version:
```
Elo   | 0.31 +- 1.92 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=16MB
LLR   | 2.91 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 33820 W: 7607 L: 7577 D: 18636
Penta | [152, 3903, 8772, 3929, 154]
https://zzzzz151.pythonanywhere.com/test/1300/
```
Renegade dev 1.1.42
Bench: 2877006

Cleaner handling of en passants

---

Renegade/Neural.h
Renegade/Utils.h
renegade-net.rs

Replacing the entire FRC data, and 1 billion positions of normal chess.
Normal chess:
```
Elo   | 3.84 +- 2.68 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.50]
Games | N: 18378 W: 4376 L: 4173 D: 9829
Penta | [95, 2138, 4523, 2335, 98]
https://zzzzz151.pythonanywhere.com/test/1388/
```
FRC:
```
Elo   | 10.20 +- 4.72 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.50]
Games | N: 5726 W: 967 L: 799 D: 3960
Penta | [36, 541, 1562, 667, 57]
https://zzzzz151.pythonanywhere.com/test/1389/
```
Bench: 2658706
Renegade dev 1.1.45

Net 28: partially regenerated training data, again

---

Renegade/Neural.h
Renegade/Utils.h
renegade-net.rs

Committing preemptively due to upcoming tournament deadlines.
Looks good at LTC:
```
Elo   | 7.34 +- 4.30 (95%)
SPRT  | 50.0+0.50s Threads=1 Hash=128MB
LLR   | 2.36 (-2.25, 2.89) [0.00, 3.50]
Games | N: 6346 W: 1439 L: 1305 D: 3602
Penta | [9, 693, 1642, 813, 16]
https://zzzzz151.pythonanywhere.com/test/1401/
```
Neutralish at STC:
```
Elo   | 0.39 +- 4.54 (95%)
LLR   | -0.18 (-2.25, 2.89) [0.00, 3.50]
Games | N: 6238 W: 1426 L: 1419 D: 3393
Penta | [30, 747, 1551, 768, 23]
https://zzzzz151.pythonanywhere.com/test/1399/
```
Passed fixed nodes:
```
Elo   | 28.92 +- 9.06 (95%)
SPRT  | N=25000 Threads=1 Hash=4MB
LLR   | 2.96 (-2.25, 2.89) [0.00, 3.50]
Games | N: 2444 W: 810 L: 607 D: 1027
Penta | [41, 225, 532, 338, 86] …
```

Net 29: increasing the hidden layer size to 1408

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Utils.h

This patch boosts history score adjustments if the pawn structure is different from when the score was last updated. The general idea is that if a history entry is stale, we should help it update more easily.
Further considerations:
- it's most likely enough to save only 8 bits per entry instead of 16
- the two tables could be rearranged in a way that the hash and the score is adjacent in memory (esp. if later tried with conthist)
- just to be sure, a simplification should be run later with always applying the larger adjustments
```
Elo   | 3.73 +- 2.60 (95%)
Games | N: 18276 W: 4096 L: 3900 D: 10280
Penta | [49, 2121, 4619, 2283, 66]
https://zzzzz151.pythonanywhere.com/test/1402/
```
Renegade dev 1.1.47
Bench: …

Increase history adjustments when pawn structures differ

---

Renegade/Search.cpp
Renegade/Utils.h

A cool idea from Alexandria's search rewrite
```
Elo   | 1.81 +- 1.47 (95%)
Games | N: 56340 W: 12302 L: 12009 D: 32029
Penta | [134, 6676, 14311, 6861, 188]
https://zzzzz151.pythonanywhere.com/test/1409/
```
Renegade dev 1.1.48
Bench: 2899227

Calculate reductions based on fail-low counts

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 3.75 +- 2.61 (95%)
Games | N: 18074 W: 4080 L: 3885 D: 10109
Penta | [50, 2088, 4573, 2269, 57]
https://zzzzz151.pythonanywhere.com/test/1417/
```
Renegade dev 1.1.50
Bench: 2731134

Only do cutoffs in qsearch when being off-PV

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 1.76 +- 1.43 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 3.50]
Games | N: 60078 W: 13315 L: 13011 D: 33752
Penta | [177, 7045, 15301, 7329, 187]
https://zzzzz151.pythonanywhere.com/test/1472/
```
Renegade dev 1.1.51
Bench: 2502361

Save best moves in qsearch too (if it raised alpha)

---

Renegade/Search.cpp
Renegade/Transpositions.cpp
Renegade/Transpositions.h
Renegade/Utils.h

Better known as ttPV, a speculative LTC was started after a few thousand games of STC:
```
Elo   | 2.13 +- 1.71 (95%)
SPRT  | 50.0+0.50s Threads=1 Hash=128MB
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.50]
Games | N: 38622 W: 8223 L: 7986 D: 22413
Penta | [38, 4401, 10203, 4624, 45]
https://zzzzz151.pythonanywhere.com/test/1482/
```
The unfinished STC:
```
Elo   | -0.12 +- 3.19 (95%)
LLR   | -0.67 (-2.25, 2.89) [0.00, 3.50]
Games | N: 11636 W: 2532 L: 2536 D: 6568
Penta | [48, 1322, 3056, 1370, 22]
https://zzzzz151.pythonanywhere.com/test/1480/
```
Renegade dev 1.1.52
Bench: 2973085

Decrease reductions in former PV nodes

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

This is being done in a bit of a silly way, because I didn't think it would pass, so will be cleaned up later.
```
Elo   | 2.66 +- 2.04 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.50]
Games | N: 28244 W: 6299 L: 6083 D: 15862
Penta | [78, 3144, 7472, 3340, 88]
https://zzzzz151.pythonanywhere.com/test/1515/
```
Renegade dev 1.1.53
Bench: 2993425

Always double extend when only having one legal move

---

Renegade/Neural.cpp
Renegade/Neural.h
Renegade/Search.h
Renegade/Utils.h

Failed(!) testing:
```
Elo   | -0.14 +- 1.64 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | -2.26 (-2.25, 2.89) [0.00, 3.50]
Games | N: 38104 W: 8784 L: 8799 D: 20521
Penta | [136, 3626, 11572, 3553, 165]
https://zzzzz151.pythonanywhere.com/test/1586/
```
However, locally it is still a statistically significant speedup of around 5%.
Since the effectiveness of this patch seems to depend on the exact machine, the code stays, but a comment is also added as a reminder to revisit the neccessary of fused updates sometime in the future.
Renegade dev 1.1.54
Bench: 2993425

Fused NNUE updates

---

Renegade/Neural.cpp
Renegade/Neural.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 12.62 +- 5.27 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=16MB
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.50]
Games | N: 4380 W: 1076 L: 917 D: 2387
Penta | [17, 419, 1171, 554, 29]
https://zzzzz151.pythonanywhere.com/test/1613/
```
Renegade dev 1.1.57
Bench: 2993425

Only recalculate the side-to-move accumulator during a refresh

---

Renegade/Move.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.81 +- 2.45 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=4MB
LLR   | 2.89 (-2.25, 2.89) [-3.50, 0.00]
Games | N: 18240 W: 4266 L: 4171 D: 9803
Penta | [78, 1781, 5328, 1834, 99]
https://zzzzz151.pythonanywhere.com/test/1650/
```
Renegade dev 1.1.63
Bench: 2993425

Implement static vectors to avoid dynamic allocations

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Utils.h

This simplifies #61, it's a bit of a bummer, but good to know nevertheless.
```
Elo   | 1.16 +- 2.20 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.50, 0.00]
Games | N: 24882 W: 5416 L: 5333 D: 14133
Penta | [74, 2897, 6414, 2984, 72]
https://zzzzz151.pythonanywhere.com/test/1666/
```
Renegade dev 1.1.66
Bench: 2816679

Always apply quiet history boost regardless of pawn structure changes

---

LICENSE
Renegade/Neural.cpp
Renegade/Neural.h
Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

This patch clearly loses at singlethreaded STC:
```
Elo   | -9.04 +- 4.84 (95%)
LLR   | -2.27 (-2.25, 2.89) [-3.50, 0.00]
Games | N: 4612 W: 929 L: 1049 D: 2634
Penta | [21, 531, 1307, 441, 6]
https://zzzzz151.pythonanywhere.com/test/1681/
```
However, it gains at 8 threads VSTC:
```
Elo   | 5.65 +- 3.31 (95%)
SPRT  | 5.0+0.05s Threads=8 Hash=64MB
Games | N: 10270 W: 2241 L: 2074 D: 5955
Penta | [16, 1091, 2760, 1246, 22]
https://zzzzz151.pythonanywhere.com/test/1682/
```
Some testing locally indicated that the regression in speed is most likely caused by the current prefetch logic becoming much less efficient, but this can be improved later. Also, the new patch crashed twice out of these ~15k games, this is …

Lazy NNUE updates

---

Renegade/Position.h
Renegade/Search.cpp
Renegade/Utils.h

Recovering some speed lost from #72 
```
Elo   | 5.51 +- 3.28 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=16MB
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.50]
Games | N: 10904 W: 2616 L: 2443 D: 5845
Penta | [54, 1064, 3056, 1211, 67]
https://zzzzz151.pythonanywhere.com/test/1688/
```
Renegade dev 1.1.68
Bench: 2816679

Prefetch transposition table earlier & based on a speculative hash

---

Renegade/Histories.cpp
Renegade/Search.cpp
Renegade/Utils.h

Combination of our 2 ideas:
1. Using average of static evaluation and raw evaluation to update correction history.
2. It is useful to allow bigger correction when using static evaluation for correction history updates (and apparently it is useful even when using both evaluations for update). 
Both ideas were neutral on their own, but together they gain elo:
```
Elo   | 3.63 +- 2.54 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.50]
Games | N: 18744 W: 4155 L: 3959 D: 10630
Penta | [62, 2106, 4838, 2306, 60]
```
Renegade dev 1.1.69
Bench: 2804167

Use the mean of raw and static evaluation in corrhist updates

---

Renegade/Search.cpp
Renegade/Search.h
Renegade/Utils.h

```
Elo   | 0.25 +- 1.53 (95%)
LLR   | 2.92 (-2.25, 2.89) [-3.50, 0.00]
Games | N: 44118 W: 9709 L: 9677 D: 24732
Penta | [87, 4540, 12779, 4560, 93]
https://zzzzz151.pythonanywhere.com/test/1743/
```
Renegade dev 1.1.72
Bench: 2792538

Simplify singular extension guard

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.34 +- 2.77 (95%)
LLR   | 2.89 (-2.25, 2.89) [-3.50, 0.00]
Games | N: 15740 W: 3490 L: 3384 D: 8866
Penta | [48, 1802, 4067, 1902, 51]
https://zzzzz151.pythonanywhere.com/test/1797/
```
Renegade dev 1.1.79
Bench: 2843759

Simplify away reducing less when in check

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.06 +- 1.66 (95%)
Games | N: 43962 W: 9825 L: 9564 D: 24573
Penta | [132, 5118, 11211, 5397, 123]
https://zzzzz151.pythonanywhere.com/test/1832/
```
Renegade dev 1.1.80
Bench: 2950436

Enable singular extensions at depth 8

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 4.14 +- 2.76 (95%)
Games | N: 15516 W: 3462 L: 3277 D: 8777
Penta | [43, 1710, 4074, 1881, 50]
https://zzzzz151.pythonanywhere.com/test/1856/
```
Renegade dev 1.1.81
Bench: 3057150

Make the history-dependent reduction term less drastic

---

Renegade/Transpositions.cpp
Renegade/Transpositions.h
Renegade/Utils.h

Organize entries in the transposition table into clusters of 4, with each being 16 bytes.
Regular STC:
```
Elo   | 8.92 +- 4.34 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.50]
Games | N: 6430 W: 1512 L: 1347 D: 3571
Penta | [14, 695, 1639, 846, 21]
https://zzzzz151.pythonanywhere.com/test/1872/
```
Hash constrained STC:
```
Elo   | 13.64 +- 5.45 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=1MB
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.50]
Games | N: 4052 W: 982 L: 823 D: 2247
Penta | [4, 423, 1024, 560, 15]
https://zzzzz151.pythonanywhere.com/test/1871/
```
Hash constrained LTC:
```
Elo   | 9.72 +- 4.51 (95%)
SPRT  | 50.0+0.50s Threads=1 Hash=16MB
Games | N: 5614 W: 1279 L: 1122 D: 3213
Penta | [3, 600, 1447, 751, 6] …
```

Organize transposition table entries into clusters

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 6.65 +- 3.44 (95%)
Games | N: 9986 W: 2276 L: 2085 D: 5625
Penta | [25, 1074, 2607, 1259, 28]
https://zzzzz151.pythonanywhere.com/test/1883/
```
Renegade dev 1.1.83
Bench: 3330333

Reverse futility pruning: return the mean of eval and beta

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 3.79 +- 2.47 (95%)
Games | N: 19600 W: 4427 L: 4213 D: 10960
Penta | [50, 2216, 5052, 2434, 48]
https://zzzzz151.pythonanywhere.com/test/1910/
```
Renegade dev 1.1.85
Bench: 3158670

Re-search deeper in LMR when the score is unexpectedly high

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.95 +- 1.55 (95%)
Games | N: 50386 W: 11203 L: 10920 D: 28263
Penta | [130, 5910, 12854, 6145, 154]
https://zzzzz151.pythonanywhere.com/test/1944/
```
Renegade dev 1.1.86
Bench: 3421739

Adjust good capture history threshold

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.95 +- 1.54 (95%)
Games | N: 50490 W: 11255 L: 10972 D: 28263
Penta | [150, 5822, 12998, 6145, 130]
https://zzzzz151.pythonanywhere.com/test/1956/
```
Renegade dev 1.1.87
Bench: 3421752

Reduce one ply more during null-move search

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 3.65 +- 2.41 (95%)
Games | N: 20298 W: 4516 L: 4303 D: 11479
Penta | [40, 2289, 5303, 2452, 65]
https://zzzzz151.pythonanywhere.com/test/1966/
```
Renegade dev 1.1.89
Bench: 3775805

On futility pruning set the score to the mean of alpha and bestscore

---

Renegade/Transpositions.cpp
Renegade/Transpositions.h
Renegade/Utils.h

```
Elo   | 13.25 +- 5.01 (95%)
Games | N: 4748 W: 1138 L: 957 D: 2653
Penta | [9, 486, 1205, 663, 11]
https://zzzzz151.pythonanywhere.com/test/1982/
```
Renegade dev 1.1.90
Bench: 3186754

New transposition table replacement scheme

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 4.32 +- 2.68 (95%)
Games | N: 16824 W: 3834 L: 3625 D: 9365
Penta | [39, 1935, 4260, 2134, 44]
https://zzzzz151.pythonanywhere.com/test/1988/
```
Renegade dev 1.1.91
Bench: 3378461

Reduce less when improving

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.82 +- 2.03 (95%)
Games | N: 28872 W: 6571 L: 6337 D: 15964
Penta | [71, 3288, 7492, 3506, 79]
https://zzzzz151.pythonanywhere.com/test/2006/
```
Renegade dev 1.1.93
Bench: 3529791

Increase importance of the captured piece type in move ordering

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 3.42 +- 2.32 (95%)
Games | N: 22850 W: 5230 L: 5005 D: 12615
Penta | [63, 2665, 5751, 2876, 70]
https://zzzzz151.pythonanywhere.com/test/2008/
```
Renegade dev 1.1.94
Bench: 3656939

Change the move count for when to start reducing

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.60 +- 1.30 (95%)
Games | N: 70632 W: 15813 L: 15488 D: 39331
Penta | [166, 8220, 18241, 8501, 188]
https://zzzzz151.pythonanywhere.com/test/2063/
```
Renegade dev 1.1.98
Bench: 4590926

Change reverse futility pruning margins

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.18 +- 1.69 (95%)
Games | N: 41618 W: 9468 L: 9207 D: 22943
Penta | [91, 4807, 10771, 5030, 110]
https://zzzzz151.pythonanywhere.com/test/2401/
```
Renegade dev 1.1.108
Bench: 4575394

Increase futility pruning margin when improving

---

Renegade/Movepicker.h
Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 2.53 +- 1.89 (95%)
Games | N: 33558 W: 7716 L: 7472 D: 18370
Penta | [77, 3888, 8628, 4086, 100]
https://zzzzz151.pythonanywhere.com/test/2416/
```
Renegade dev 1.1.111
Bench: 4109358

Replace refutation ordering with a simple bonus

---

Renegade/Movepicker.h
Renegade/Utils.h

```
Elo   | 2.64 +- 1.95 (95%)
Games | N: 31796 W: 7221 L: 6979 D: 17596
Penta | [82, 3685, 8125, 3921, 85]
https://zzzzz151.pythonanywhere.com/test/2499/
```
Renegade dev 1.1.116
Bench: 4565592

Tuned refutations (80k games @ 10+0.1)

---

Renegade/Histories.cpp
Renegade/Histories.h
Renegade/Search.cpp
Renegade/Utils.h

A neat idea originally from Alexandria rewrite
```
Elo   | 3.35 +- 2.29 (95%)
Games | N: 22922 W: 5291 L: 5070 D: 12561
Penta | [48, 2640, 5882, 2825, 66]
https://zzzzz151.pythonanywhere.com/test/2526/
```
Renegade dev 1.1.117
Bench: 4735873

Apply move ordering bonuses as many times as failing high

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.88 +- 1.50 (95%)
Games | N: 52620 W: 12007 L: 11722 D: 28891
Penta | [117, 6074, 13659, 6327, 133]
https://zzzzz151.pythonanywhere.com/test/2548/
```
Renegade dev 1.1.118
Bench: 4635612

Don't SEE prune in main search when the destination square is safe

---

Renegade/Search.cpp
Renegade/Utils.h

Fixed 5k nodes as a stress test:
```
Elo   | 21.94 +- 7.80 (95%)
SPRT  | N=5000 Threads=1 Hash=2MB
Games | N: 4202 W: 1453 L: 1188 D: 1561
Penta | [133, 430, 777, 561, 200]
https://zzzzz151.pythonanywhere.com/test/2552/
```
Sanity test with 4 threads looks alright as well.
Renegade dev 1.1.119
Bench: 4635612

No longer write to TT and histories when aborting search

---

Renegade/Search.cpp
Renegade/Utils.h

Now the engine (finally) generates quiet moves in quiescence search, and returns a checkmate value if no legal moves found
```
Elo   | 2.81 +- 2.68 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 0.00]
Games | N: 16712 W: 3841 L: 3706 D: 9165
Penta | [40, 1941, 4253, 2088, 34]
https://zzzzz151.pythonanywhere.com/test/2653/
```
Renegade dev 1.1.121
Bench: 5120119

Prove checkmates in quiescence search

---

Renegade/Neural.h
Renegade/Utils.h
renegade-net.rs

```
Elo   | 6.93 +- 3.58 (95%)
Games | N: 9980 W: 2501 L: 2302 D: 5177
Penta | [38, 1127, 2464, 1320, 41]
https://zzzzz151.pythonanywhere.com/test/2720/
```
```
Elo   | 8.07 +- 3.78 (95%)
SPRT  | 50.0+0.50s Threads=1 Hash=128MB
Games | N: 7884 W: 1935 L: 1752 D: 4197
Penta | [7, 839, 2070, 1016, 10]
https://zzzzz151.pythonanywhere.com/test/2722/
```
Trained on 5.66 billion positions for 800 superbatches in total, and now also includes positions from 10k soft nodes datagen
Renegade dev 1.1.128
Bench: 4510003

Net 31: Two-stage net with more data, 14 buckets and hl 1600

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 0.81 +- 1.78 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.00, 0.00]
Games | N: 37522 W: 8570 L: 8482 D: 20470
Penta | [90, 4399, 9683, 4511, 78]
https://zzzzz151.pythonanywhere.com/test/2755/
```
Renegade dev 1.1.132
Bench: 5009878

Actually prove checkmates in quiescence search

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 3.02 +- 2.14 (95%)
Games | N: 26216 W: 6034 L: 5806 D: 14376
Penta | [51, 3051, 6695, 3241, 70]
https://zzzzz151.pythonanywhere.com/test/2765/
```
Renegade dev 1.1.133
Bench: 4939303

Futility prune in quiescence search

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.47 +- 2.10 (95%)
LLR   | 2.89 (-2.25, 2.89) [-3.00, 0.00]
Games | N: 26202 W: 6050 L: 5939 D: 14213
Penta | [60, 2986, 6896, 3101, 58]
https://zzzzz151.pythonanywhere.com/test/2766/
```
Renegade dev 1.1.134
Bench: 4906738

Break out of qsearch moves loop when it makes sense

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.41 +- 1.14 (95%)
Games | N: 81092 W: 18908 L: 18580 D: 43604
Penta | [153, 8495, 22935, 8797, 166]
https://zzzzz151.pythonanywhere.com/test/2883/
```
Bench: 4992978
Renegade dev 1.2.1

Slightly increase the minimum search time

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.38 +- 1.11 (95%)
Games | N: 96074 W: 22292 L: 21911 D: 51871
Penta | [239, 11199, 24747, 11646, 206]
https://zzzzz151.pythonanywhere.com/test/2939/
```
Renegade dev 1.2.2
Bench: 4877771

No longer save some scores in qsearch as exact

---

Renegade/Neural.cpp
Renegade/Utils.h

```
Elo   | 2.96 +- 2.07 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=8MB
Games | N: 25248 W: 6214 L: 5999 D: 13035
Penta | [101, 2399, 7447, 2538, 139]
https://zzzzz151.pythonanywhere.com/test/3014/
```
Renegade dev 1.2.3
Bench: 4877771

Fuse update operations for cached accumulators

---

Renegade/Search.cpp
Renegade/Utils.h

```
Elo   | 1.37 +- 2.08 (95%)
LLR   | 2.92 (-2.25, 2.89) [-3.00, 0.00]
Games | N: 28058 W: 6564 L: 6453 D: 15041
Penta | [72, 3304, 7176, 3395, 82]
https://zzzzz151.pythonanywhere.com/test/3017/
```
Renegade dev 1.2.4
Bench: 4217178

Remove depth condition from main search SEE

---

Renegade/Magics.cpp
Renegade/Magics.h
Renegade/Position.cpp
Renegade/Position.h
Renegade/Utils.h

```
Elo   | 5.06 +- 2.97 (95%)
Games | N: 14008 W: 3375 L: 3171 D: 7462
Penta | [33, 1611, 3535, 1769, 56]
https://zzzzz151.pythonanywhere.com/test/3062/
```
A really cool idea from pawnocchio
Renegade dev 1.2.6
Bench: 4408162

Account for pinned pieces when calculating SEE
